services:
  postgres:
    image: postgres:16.4
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daster
      POSTGRES_DB: postapi
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  post-api:
    image: post-api:latest
    build: .
    restart: "no"
    ports:
      - "667:667"
    environment:
      POSTGRES_HOST: postgres:5432
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:667/actuator/health || exit 1"
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - postgres

volumes:
  postgres_data: